version: '3'

services:
  structure-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the entire app directory for development
      - ./:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # Override the CMD in Dockerfile to use Flask's development server for hot-reloading
    command: flask run --host=0.0.0.0 --port=5000